---
- name: Remove web_app
  block:
  - name: Remove container
    docker_container:
      name: "{{ container_name }}"
      state: absent

  - name: Remove image
    docker_image:
      name: "{{ image_name }}"
      force: true
      state: absent

  when: web_app_full_wipe | bool
  tags:
    - wipe