version: "3.7"

services:
  promtail:
    image: grafana/promtail:2.9.2
    container_name: promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
      - ./configs/promtail.yml:/etc/promtail/config.yml
    command:
      - "--config.file=/etc/promtail/config.yml"
      - "--config.expand-env=true"
    logging:
      driver: "json-file"
      options:
        tag: "{{ .Name }}"
        max-size: "100m"
        max-file: "5"
    deploy:
      resources:
        limits:
          memory: "200m"
    ports:
      - "9080:9080"

  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/config.yml
    volumes:
      - ./configs/loki.yml:/etc/loki/config.yml
    logging:
      driver: "json-file"
      options:
        tag: "{{ .Name }}"
        max-size: "100m"
        max-file: "5"
    deploy:
      resources:
        limits:
          memory: "200m"

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./configs/grafana-provisioning:/etc/grafana/provisioning
      - ./provisioning/grafana-dashboards:/var/lib/grafana/dashboards
    logging:
      driver: "json-file"
      options:
        tag: "{{ .Name }}"
        max-size: "100m"
        max-file: "5"
    deploy:
      resources:
        limits:
          memory: "200m"
    ports:
      - "3000:3000"
    

  prometheus:
    image: prom/prometheus:v2.5.0
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/config.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/config.yml
    logging:
      driver: "json-file"
      options:
        tag: "{{ .Name }}"
        max-size: "100m"
        max-file: "5"
    deploy:
      resources:
        limits:
          memory: "200m"

  app_python:
    image: habur331/devops-course:latest
    container_name: app_python
    ports:
      - 80:5000
    environment:
      VISIT_COUNTER_PATH: '/etc/app_python/tmp/visits.txt'
    volumes:
      - ../app_python/tmp/:/etc/app_python/tmp
    logging:
      driver: "json-file"
      options:
        tag: "{{ .Name }}"
        max-size: "100m"
        max-file: "5"
    deploy:
      resources:
        limits:
          memory: "200m"
