positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: containers
  static_configs:
    - targets:
        - localhost
      labels:
        job: containerlogs
        __path__: /var/lib/docker/containers/*/*log # For linux only
  pipeline_stages:
    - json:
        expressions:
          log: log
          stream: stream
          attrs: attrs
          tag: attrs.tag
          time: time
    - timestamp:
        format: RFC3339Nano
        source: time
    - regex:
        expression: "^/var/lib/docker/containers/(?P<container_id>.{12}).+/.+-json.log$"
        source: filename
    - labels:
        stream:
        container_id:
        tag:
    - output:
        source: log