name: Python CI

on:
  push:
    paths:
      - "app_python/**"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
       python-version: '3.11'

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/app_python/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: app_python

    - name: Run linter
      run: |
        pip install flake8
        flake8 --ignore=F401
      working-directory: app_python

    - name: Run tests
      run: |
        python -m unittest discover -s .
      working-directory: app_python

    - name: Run Snyk check
      run: |
        npm install -g snyk
        snyk auth ${{ secrets.SNYK_TOKEN }}
        snyk test
      working-directory: app_python

    - name: Docker login
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      run: |
        docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/devops-course --push .
      working-directory: app_python